// import { MD3Colors } from 'react-native-paper/lib/typescript/src/types';
export const lightColors = {
  primary: '#655BE0',
  primaryContainer: '#655BE0',
  secondary: '#FAFAFA',
  secondaryContainer: '#FAFAFA',
  tertiary: '#F8EFFB',
  tertiaryContainer: '#523DA2',
  surface: '#FFFFFF',
  surfaceVariant: '',
  surfaceDisabled: 'grey',
  background: '#FFFFFF',
  error: '#FF524F',
  errorContainer: 'rgba(255, 82, 79, 0.2)',
  onPrimary: '#FFFFFF',
  onPrimaryContainer: '#FFFFFF',
  onSecondary: '#808080',
  onSecondaryContainer: '#808080',
  onSurface: '#FFFFFF',
  onBackground: '#3A3A3A',
  onErrorContainer: '#FF524F',
}

export const darkColors = {
  primary: '#655BE0',
  primaryContainer: '#655BE0',
  secondary: '#FAFAFA',
  secondaryContainer: '#FAFAFA',
  tertiary: '#F8EFFB',
  tertiaryContainer: '#523DA2',
  surface: '#FFFFFF',
  surfaceVariant: '',
  surfaceDisabled: 'grey',
  background: '#0D0D0D',
  error: '#FF524F',
  errorContainer: 'rgba(255, 82, 79, 0.2)',
  onPrimary: '#FFFFFF',
  onPrimaryContainer: '#FFFFFF',
  onSecondary: '#808080',
  onSecondaryContainer: '#808080',
  onSurface: '#FFFFFF',
  onBackground: '#FFFFFF',
  onErrorContainer: '#FF524F',
}